# Generated by Django 6.0.1 on 2026-01-23 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='currency',
            name='symbol',
            field=models.CharField(default='', max_length=10),
        ),
    ]
